### PR TITLE
Add ikvm-base plugin

### PR DESCRIPTION
**Pull request by timotei**
This will allow us to use the bare minimum,
without having the tasks created, even if we don't
care about them.

### CODE REVIEW

**Comment by timotei** [comment]
If we *create* an IKVM task (the one that is created by default) we get access to the ikvmCompile configuration.

Now, a question is the following: do we want to create that by default in the base or not? It would allow us to have both the "generic" ikvmCompile and keep the current code in the IKVM class as well, and generate ikvm<configuration name>Compile for other types of IKVM too.

**Comment by gluck** [comment]
You want to have the ikvmCompile configuration defined in base and somehow conventioned into each ikvm task? Not sure I get it

**Comment by timotei** [comment]
Yup, something like that. Not sure if it makes sense or not though.

**Comment by gluck** [comment]
When having multiple IKVM tasks is used for multiple IKVM versions, maybe it won't, as the deps can't be reused no ?
Other use cases for multiple IKVM tasks may exist, but I'd leave up to them (for now at least) to factor their dependencies.

**Comment by timotei** [comment]
OK, we can keep deps separate then.

**Pull request merged**
